"""brand config: engines, frequency, locale

Revision ID: 27cd93d8ab92
Revises: 68ad00285ad8
Create Date: 2026-07-14 09:13:31.980206
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '27cd93d8ab92'
down_revision: Union[str, None] = '68ad00285ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('tracked_engines', postgresql.ARRAY(sa.String()), server_default='{openai}', nullable=False))
    op.add_column('brands', sa.Column('run_frequency', sa.String(length=16), server_default='daily', nullable=False))
    op.add_column('brands', sa.Column('location', sa.String(length=128), nullable=True))
    op.add_column('brands', sa.Column('language', sa.String(length=8), server_default='en', nullable=False))
    op.add_column('brands', sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'last_run_at')
    op.drop_column('brands', 'language')
    op.drop_column('brands', 'location')
    op.drop_column('brands', 'run_frequency')
    op.drop_column('brands', 'tracked_engines')
    # ### end Alembic commands ###
