"""initial schema

Revision ID: 68ad00285ad8
Revises: 
Create Date: 2026-07-13 18:01:26.165052
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '68ad00285ad8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('engines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('competitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_brand_id'), 'competitors', ['brand_id'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intent_type', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_brand_id'), 'prompts', ['brand_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('engine_id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visibility_score', sa.Float(), nullable=False),
    sa.Column('share_of_voice', sa.Float(), nullable=False),
    sa.Column('mention_rate', sa.Float(), nullable=False),
    sa.Column('citation_rate', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'engine_id', 'window_start', 'window_end', name='uq_score_window')
    )
    op.create_index(op.f('ix_scores_brand_id'), 'scores', ['brand_id'], unique=False)
    op.create_index(op.f('ix_scores_engine_id'), 'scores', ['engine_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('engine_id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('raw_response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_engine_id'), 'runs', ['engine_id'], unique=False)
    op.create_index(op.f('ix_runs_prompt_id'), 'runs', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_runs_run_at'), 'runs', ['run_at'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_domain'), 'citations', ['domain'], unique=False)
    op.create_index(op.f('ix_citations_run_id'), 'citations', ['run_id'], unique=False)
    op.create_table('mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('is_tracked_brand', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('prominence', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentions_run_id'), 'mentions', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentions_run_id'), table_name='mentions')
    op.drop_table('mentions')
    op.drop_index(op.f('ix_citations_run_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_domain'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_runs_run_at'), table_name='runs')
    op.drop_index(op.f('ix_runs_prompt_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_engine_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_scores_engine_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_brand_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_prompts_brand_id'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_competitors_brand_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_table('engines')
    op.drop_table('brands')
    # ### end Alembic commands ###
